### ISSUE TITLE
I wonder if "Tile" is overemphasized in the package

### ISSUE THREAD

**Issue by alex-s-gardner** [asinghvi17/RangeExtractor.jl#2]
I understand the the power of the package is to chop up the I/O and operations into tiles (for efficient I/O and memory)... but does the user need to know this? The user probably just cares that this package offers a solution to large out of memory computations that operate on subsets of the data. How that is handed internally is probably irrelevant to the user. 

One still needs to expose things like `tiling_scheme` but only an expert user should need to know about it. 

What about a package name like:
`SpeedyZonalOps`
`SpeedyZonal`
`ScalableZonalOps`
`ScalableZonal`

Less emphasis should probably be placed on the Tiles as these are just a means to an end

**Comment by asinghvi17** [comment]
True, we can definitely rename.  Maybe RangeExtractor.jl?

**Comment by alex-s-gardner** [comment]
RangeExtractor.jl makes more sense... especially if extract(array, ranges), without kwargs, returned the raw values of array

**Comment by asinghvi17** [comment]
This is also an extremely good point.

Right now I'm in the middle of a refactor that allows the operator to be a lot more flexible.  Given that, it's not out of the question for the default operator to be a `RecombinantTileOperator` (name TBD) that just reassembles the array of each extent as it reads.

Then, the user facing API would be:
```julia
	extract([f = identity], data::AbstractArray, ranges, [metadata = nothing]; strategy, threaded, progress)

Extract `ranges` from `data`, and apply `f` to the resulting arrays (essentially `[f(data[range]) for range in ranges]`).
```

so `extract(array, ranges)` just returns a vector of materialized matrices, but you can also pass a function like `sum`, etc that does its own thing.  I'm also leaning towards not passing any metadata if `metadata = nothing`.

Things like zonal would get their own custom config, so we can cut down on memory use.

**Comment by alex-s-gardner** [comment]
Why is metadata needed?

**Comment by asinghvi17** [comment]
Zonal needs a geometry for each tile, for instance.

**Comment by alex-s-gardner** [comment]
This seems a bit cumbersome, no?

What if "ranges" could be a "geometry" or a "range".. if passed geometry then the range would be calculated internal to extract

**Comment by asinghvi17** [comment]
There's still no way to generically know what arguments the function wants, unless you specify it using an operator though?

Ideally extract is very low level and underpins Rasters.jl etc, so users only really have to know about tiling strategies...
