### ISSUE TITLE
Large scale test case fails with reasonable_strategy not defined

### ISSUE THREAD

**Issue by felixcremer** [asinghvi17/RangeExtractor.jl#7]
When I try to run the large scale test case this fails with the error:

```julia
julia> results =  RangeExtractor.extract(array, ranges; operation = op, tiling_scheme = strategy, combine = identity, threaded = false)
ERROR: UndefVarError: `reasonable_strategy` not defined in `RangeExtractor`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] top-level scope
   @ REPL[18]:1
```
The function runs if I set the strategy keyword to the strategy defined earlier in the script.

**Comment by asinghvi17** [comment]
Hm, it looks like i didn't update that to the latest syntax.  Will push a fix soon.  But the README has the new syntax (it's a bit more user friendly).

**Comment by asinghvi17** [comment]
Fixed in https://github.com/asinghvi17/RangeExtractor.jl/commit/621538d2e1b2cba20d2e11a1ec8558ed4c73784c, thanks!
