### ISSUE TITLE
can FixedGridTiling be rectangular? 

### ISSUE THREAD

**Issue by alex-s-gardner** [asinghvi17/RangeExtractor.jl#8]
Just wondering if  FixedGridTiling supports rectangular tiles.. and if that's something that should be supported

**Comment by asinghvi17** [comment]
It does!  The only thing it doesn't support is irregular tiling, yet.

You can pass an n-tuple of chunk sizes, one per dimension.

**Comment by rafaqz** [comment]
What about tiling with overlaps? I'm keen to add that here somehow either way.

**Comment by asinghvi17** [comment]
Hmm that would need a separate tiling scheme.   But nothing fundamentally stops you from doing that...
